server:
  port: ${APPLICATION_PORT:5000}
  servlet:
    contextPath: /api
  auth:
    username: ${API_USERNAME:admin}
    password: ${API_PASSWORD:admin}

spring:
  main:
    banner-mode: 'off'
  application:
    name: backend-challenge
    version: v1
    swagger:
      title: ${spring.application.name} - API
      description: Documentation
      terms-of-service-url: https://github.com/brow-joe/backend-challenge
      license: public
      license-url: https://github.com/brow-joe/backend-challenge
  jackson:
    default-property-inclusion: NON_DEFAULT
  cloud:
    config:
      enabled: false
  profiles:
    active: local

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.string}
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 1
    statusPageUrl: http://${eureka.hostname}:${server.port}${server.servlet.contextPath}/swagger-ui.html
  client:
    enabled: ${DISCOVERY_ENABLED:false}
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:http://localhost:8761}/eureka/

---
spring:
  profiles: local
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:db4free.net}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:brwchallenge}
    username: ${MYSQL_USERNAME:backendchallenge}
    password: ${MYSQL_PASSWORD:Axqdjfjj}
---
spring:
  profiles: test
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:brwchallenge;MODE=MySQL;DB_CLOSE_DELAY=-1;user=backendchallenge;password=Axqdjfjj
    username: backendchallenge
    password: Axqdjfjj
    validationQuery: SELECT 1
  jpa:
    hibernate:
      ddl-auto: create
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
---